import Navbar from "@/components/Navbar";
import "./globals.css";
import Provider from "@/components/Provider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Provider>
				<body className="h-screen max-w-7xl mx-auto bg-black text-white ">
					<Navbar />

					{children}
				</body>
			</Provider>
		</html>
	);
}
